apiVersion: kyverno.io/v1
kind: Policy 
metadata:
    name: validation-for-deployment
    namespace: demo
spec:
    validationFailureAction: Enforce # Audit
    rules:
      - name: check-for-team-label
        match:
          any:
            - resources:
                kinds:
                 - Deployment
        validate:
           message: "The label 'team' is required for all deployments."
           pattern:
             metadata:
               labels:
                 team: "?*"
      - name: check-for-replica
        match:
          any:
            - resources:
                kinds:
                 - Deployment
        validate:
           message: "The replica must set to >=3"
           pattern:
             spec:
               replicas: ">=3" 
