apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole 
metadata: 
  labels:
    rbac.kyverno.io/aggregate-to-admission-controller: "true"
    rbac.kyverno.io/aggregate-to-background-controller: "true"
  name: kyverno:read-secrets
rules:
- apiGroups:
  - ""
  resources:
  - secrets 
  verbs:
  - list
  - get
  - update
  - create
  - delete